default: &default
  title: yportal
  host: localhost:3000

  mailer:
    # For localhost postfix
    smtp_settings:
      address: "smtp.gmail.com"
      port: 587
      enable_starttls_auto: false
      domain: "gmail.com"
      user_name: 
      password: 
      authentication: "plain"
      enable_starttls_auto: true
    default_options:
      from: no-reply@example.com
    default_url_options:
      host: localhost:3000

development:
  <<: *default
  customer_service_email:
    # - kailaichao@cloudchain.cn

develop:
  <<: *default
  customer_service_email:
    # - kailaichao@cloudchain.cn

test:
  <<: *default
  customer_service_email:
    # - kailaichao@cloudchain.cn

production:
  <<: *default

  customer_service_email:
    # - kailaichao@cloudchain.cn
